import type { NextPage } from 'next';
import Head from 'next/head';
import Nav from '../components/Nav';
import Hero from '../components/Hero';
import styles from '../styles/Home.module.css';
import Projects from '../components/Projects';
//import Contact from '../components/Contact';
import dynamic from 'next/dynamic';

const Contact = dynamic(() => import('../components/Contact'));

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Inspire Digital</title>
        <meta
          name='description'
          content='Generated by create next app, inspire digital company landing'
        />
        <link rel='icon' href='/sun-icon.svg' />
      </Head>
      <Nav />
      <Hero />
      <Projects />
      <Contact />
      <footer className={styles.footer}>
        <a
          href='https://github.com/keremduran'
          target='_blank'
          rel='noopener noreferrer'
        >
          Developed by Kerem Duran
        </a>
      </footer>
    </div>
  );
};

export default Home;
